apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: isen2021
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: webserver-secret
          mountPath: "/var/secret"
          readOnly: true
      volumes:
      - name: webserver-secret
        secret:
        secretName: webserver-secret
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer