name: Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.yowank }}
            password: ${{ secrets.yowan1234 }}
            registry: docker.io
            repository: YowanK/cd
            tag_with_sha: true